config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :providers, only: [:index, :new, :create]

  resources :services, shallow: true, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:show, :new, :create] do
      resources :payments, only: [:new, :create]
      resources :reviews, only: [:new, :create]
    end
    resources :service_statistics, only: [:show]
  end
  resources :service_statistics, only: [:index]

  resources :bookings, only: [:index]

  resources :customers, only: [:index, :show, :new, :create]

  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback" => "callbacks#google_oauth2_response"
  root "statics#index"
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :organizations

  has_one :user, as: :person, dependent: :destroy
  accepts_nested_attributes_for :user

  has_many :services, dependent: :destroy
  has_many :bookings, through: :services
  def sid_list
    services.pluck(:id)
  end

  def previous_year_bookings
    bookings.where(time_end: Time.now.beginning_of_year-1.year..Time.now.end_of_year-1.year)
  end

  def current_year_bookings
    bookings.where(time_end: Time.now.beginning_of_year..Time.now.end_of_year)
  end

  def revenue_data(year)
    revenue_data = []
    months = %w(jan feb mar apr may jun jul aug sep oct nov dec)
    months.each do |month|
      month_revenue = []
      services.each do |service|
        month_revenue << service.monthly_revenue(year, month)
      end
      revenue_data << month_revenue.reduce(:+)
    end
    revenue_data.include?(nil) ? [0] : revenue_data
  end

  def booking_data(year)
    booking_data = []
    months = %w(jan feb mar apr may jun jul aug sep oct nov dec)
    months.each do |month|
      month_booking = []
      services.each do |service|
        month_booking << service.monthly_booking(year, month)
      end
      booking_data << month_booking.reduce(:+)
    end
    booking_data.include?(nil) ? [0] : booking_data
  end

  def annual_revenue
    revenue_data(Time.current.year).reduce(:+)
  end

  def annual_bookings
    booking_data(Time.current.year).reduce(:+)
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
    @services = Service.provider_services(provider)
    @booking = provider.bookings
    @revenue_data = chart_data(provider.revenue_data(previous_year),
                               provider.revenue_data(current_year))
    @booking_data = chart_data(provider.booking_data(previous_year),
                               provider.booking_data(current_year))
  end

  def new
    @provider = Provider.new
    @provider.build_user
    session[:additional] = 'Provider'
  end

  def create
    @provider = Provider.create
    @provider.user = @provider.build_user(provider_params[:user_attributes])
    @provider.user.person = @provider
    if @provider.save
      redirect_to new_session_path
    else
      render new_provider_path
    end
  end

  private

  def provider_params
    params.require(:provider).permit(user_attributes: [:first_name,
                                                       :last_name,
                                                       :email,
                                                       :phone_number,
                                                       :gender,
                                                       :password,
                                                       :password_confirmation])
  end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_appointments.html.erb
<div class="col-md-12">
  <% @services.each do |service| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= service.name %></h3>
    </div>
    <table class="table table-bordered">
      <tr>
        <td>
          Appointment Date
        </td>
        <td>
          Client
        </td>
      </tr>
      <% future_bookings(service).each do |booking| %>
      <tr>
        <td>
          <%= booking.time_start %>
        </td>
        <td>
          <%= booking.customer.user.first_name %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <% end %>
</div>

app/views/providers/_appointments_history.html.erb
<div class="col-md-12">
  <% @services.each do |service| %>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= service.name %></h3>
    </div>
    <table class="table table-bordered">
      <tr>
        <td>
          appointment date
        </td>
        <td>
          created at
        </td>
        <td>
          client
        </td>
      </tr>
      <% service.bookings.each do |booking| %>
      <tr>
        <td>
          <%= booking.time_start %>
        </td>
        <td>
          <%= booking.created_at %>
        </td>
        <td>
          <%= booking.customer.user.first_name %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
  <% end %>
</div>

app/views/providers/_overview.html.erb
<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Revenue</h3>
    </div>
      <li class="list-group-item col-md-6">Annual Revenue
        <span class="label label-default">
          <%= number_to_currency(provider.annual_revenue) %>
        </span>
      </li>
      <li class="list-group-item col-md-6">Lifetime Revenue
        <span class="label label-default">

        </span>
      </li>
    <%= line_chart @revenue_data, chart_options %>
  </div>
</div>

<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Appointments</h3>
    </div>
    <li class="list-group-item col-md-6">Annual Appointments
      <span class="label label-default">
        <%= provider.annual_bookings %>
      </span>
    </li>
    <li class="list-group-item col-md-6">Lifetime Appointments
      <span class="label label-default">
      </span>
    </li>
    <%= bar_chart @booking_data, chart_options %>
  </div>
</div>

app/views/providers/_services.html.erb
<% @services.each do|service| %>
  <div class="col-md-4">
    <div class="panel panel-primary" data-href="<% link_to service_path(service) %>">
      <div class="panel-heading">
        <%= service.name %>
        <br>
        $<%= service.rate %>
      </div>
      <div class="panel-body">
        <p>
          <%#= service.description %>
          Service Description Goes Here
          Add service created at date
          add weekly figures
        </p>
        <%= link_to "Details", service_path(service), class:'btn btn-default col-md-12' %>
      </div>
    </div>
  </div>
<% end %>

app/views/providers/index.html.erb
<div class="container-fluid">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#overview" aria-controls="Overview" role="tab" data-toggle="tab">Overview</a></li>
    <li role="presentation"><a href="#appointments" aria-controls="Appointments" role="tab" data-toggle="tab">Appointments</a></li>
    <li role="presentation"><a href="#history" aria-controls="History" role="tab" data-toggle="tab">History</a></li>
    <li role="presentation"><a href="#extratab" aria-controls="ExtraTab" role="tab" data-toggle="tab">Services</a></li>
  </ul>
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="overview"><%= render partial: "overview" %></div>
    <div role="tabpanel" class="tab-pane" id="appointments"><%= render partial: "appointments" %></div>
    <div role="tabpanel" class="tab-pane" id="history"><%= render partial: "appointments_history" %></div>
    <div role="tabpanel" class="tab-pane" id="extratab"><%= render partial: "services" %></div>
  </div>
</div>

app/views/providers/new.html.erb
<div class="col-md-6">
  <div class="panel panel-primary sign-up-form">
    <div class="panel-heading">
      <h3 class="panel-title">Create a TRIMMER Account</h3>
    </div>
    <div class="panel-body">
      <%= simple_form_for @provider do |p| %>
      <%= p.simple_fields_for :user do |user| %>
      <%= user.input :first_name %>
      <%= user.input :last_name %>
      <%= user.input :email %>
      <%= user.input :phone_number %>
      <%= user.input :gender %>
      <%= user.input :password %>
      <%= user.input :password_confirmation %>
      <% end %>
      <%= p.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="panel panel-primary sign-up-form">
    <div class="panel-heading">
      <h3 class="panel-title">Or</h3>
    </div>
    <div class="panel-body">
      <%= link_to "Sign Up With Google", sign_in_with_google_path %>
    </div>
  </div>
</div>