config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :providers, only: [:index, :new, :create]

  resources :services, shallow: true, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:show, :new, :create] do
      resources :payments, only: [:new, :create]
      resources :reviews, only: [:new, :create]
    end
    resources :service_statistics, only: [:show]
  end
  resources :service_statistics, only: [:index]

  resources :bookings, only: [:index]

  resources :customers, only: [:index, :show, :new, :create]

  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback" => "callbacks#google_oauth2_response"
  root "statics#index"
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :provider
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many :customers, through: :bookings

  validates :name, presence: true
  validates :rate, presence: true
  validates :location, presence: true
  validates :duration, presence: true
  validates :provider_id, presence: true

  geocoded_by :address
  after_validation :geocode

  def self.provider_services(user)
    Service.where(provider_id: user)
  end

  def monthly_revenue(year, month)
    bookings.where(time_end: Time.mktime(year, month).all_month).count * self.rate
  end

  def monthly_booking(year, month)
    bookings.where(time_end: Time.mktime(year, month).all_month).count
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = provider.services
  end

  def show
    @service = Service.find params[:id]
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new service_params
    @service.provider_id = current_user.person_id
    if @service.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def service_params
    params.require(:service).permit(:name, :rate, :certified, :location, :duration)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def services_json(services)
    Gmaps4rails.build_markers(services) do |service, marker|
      service_booking = link_to "Book TRIM", new_service_booking_path(service)
      marker.lat        service.latitude
      marker.lng        service.longitude
      marker.infowindow gmaps4rails_service_infowindow(service) + service_booking
    end
  end

  def gmaps4rails_service_infowindow(service)
    "<h4>#{service.name}</h4>" +
    "<h6>#{service.provider.user.first_name}</h6>" +
    "<p>Price: #{cost(service)}</p>"
  end

  def cost(service)
    number_to_currency(service.rate)
  end
end

app/views/services/index.html.erb
<div class="container-fluid">
  <ul class="nav nav-tabs">
    <li class="active navigation">
      <%= link_to "Add Service", new_service_path%>
    </li>
    <li>
      <%= link_to "My Services", services_path%>
    </li>
  </ul>
</div>

<div class="container-fluid">
  <% @services.each do|service| %>
    <div class="col-md-4">
      <div class="panel panel-primary service-panel" data-href="<% link_to service_path(service) %>">
        <div class="panel-heading">
          <%= link_to "#{service.name}", service_path(service) %>
          <br>
          $<%= service.rate %>
        </div>
        <div class="panel-body">
          <p>
            <%#= service.description %>
            Service Description Goes Here
            Add service created at date
            add weekly figures
          </p>
        </div>
        <table class="table  table-bordered ">
          <tr>
            <td>
              Past Bookings
            </td>
            <td>
              Future Bookings
            </td>
            <td>
              Today's bookings
            </td>
          </tr>
          <tr>
            <td>
              <%= past_bookings(service) %>
            </td>
            <td>
              <%= future_bookings(service) %>
            </td>
            <td>
              <%= current_bookings(service) %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/services/new.html.erb
<div class="col-md-3">

</div>

<div class="col-md-6">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Create a new service</h3>
    </div>
    <div class="panel-body">
      <%= simple_form_for @service do |s| %>
      <%= s.input :name%>
      <%= s.input :rate %>
      <%= s.input :location %>
      <%= s.input :duration %>
      <%= s.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-3">

</div>

app/views/services/show.html.erb
<div class="col-md-1"></div>
<div class="col-md-10">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title"><%= @service.name %></h2>
    </div>
    <div class="panel-body">
      Current Rate: $<%= @service.rate %> | Current Location: <%= @service.location %> | <%= link_to 'Statistics', service_statistic_path(@service) %>
    </div>
  </div>
</div>
<div class="col-md-1"></div>

<div class="col-md-6">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Current Bookings</h3>
    </div>
    <table class="table  table-bordered">
      <tr>
        <td>
          Customer Name
        </td>
        <td>
          Booking Created
        </td>
        <td>
          Booking Date
        </td>
        <td>
          Booking Completed?
        </td>
        <td>
          Tip
        </td>
      </tr>
      <% @service.bookings.where('time_end > ?', Time.now).each do |booking| %>
      <tr>
        <td>
          <%= booking.customer.user.first_name %> <%= booking.customer.user.last_name %>
        </td>
        <td>
          <%= booking.created_at.to_formatted_s(:long_ordinal) %>
        </td>
        <td>
          <%= booking.time_start.to_formatted_s(:long_ordinal) %>
        </td>
        <td>
          AASM STATE
        </td>
        <td>
          tip here
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

<div class="col-md-6">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h3 class="panel-title">Completed Bookings</h3>
    </div>
    <table class="table  table-bordered">
      <tr>
        <td>
          Customer Name
        </td>
        <td>
          Booking Created
        </td>
        <td>
          Booking Date
        </td>
        <td>
          Booking Completed?
        </td>
        <td>
          Tip
        </td>
        <td>
          Review
        </td>
      </tr>
      <% @service.bookings.where('time_end < ?', Time.now).each do |booking| %>
      <tr>
        <td>
          <%= booking.customer.user.first_name %> <%= booking.customer.user.last_name %>
        </td>
        <td>
          <%= booking.created_at.to_formatted_s(:long_ordinal) %>
        </td>
        <td>
          <%= booking.time_start.to_formatted_s(:long_ordinal) %>
        </td>
        <td>
          AASM STATE
        </td>
        <td>
          tip here
        </td>
        <td>
          <%= booking.reviews.first.rating %>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>