config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :providers, only: [:index, :new, :create]

  resources :services, shallow: true, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:show, :new, :create] do
      resources :payments, only: [:new, :create]
      resources :reviews, only: [:new, :create]
    end
    resources :service_statistics, only: [:show]
  end
  resources :service_statistics, only: [:index]

  resources :bookings, only: [:index]

  resources :customers, only: [:index, :show, :new, :create]

  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback" => "callbacks#google_oauth2_response"
  root "statics#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :user, as: :person, dependent: :destroy
  accepts_nested_attributes_for :user

  has_many :bookings, dependent: :destroy
  has_many :booked_services, through: :bookings, source: :service

  has_many :reviews, dependent: :destroy
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @bookings = current_user.person.bookings.where('created_at >= ?', 1.week.ago).order(created_at: :desc)
    @services = Service.where.not(latitude: nil)
  end

  def show
    @bookings = current_user.person.bookings.order(time_start: :desc)
  end

  def new
    @customer = Customer.new
    @customer.build_user
    session[:additional] = 'Customer'
  end

  def create
    @customer = Customer.create
    @customer.user = @customer.build_user(customer_params[:user_attributes])
    @customer.user.person = @customer
    if @customer.save
      redirect_to new_session_path
    else
      render new_customer_path
    end
  end

  private

  def customer_params
    params.require(:customer).permit(user_attributes: [:first_name,
                                                       :last_name,
                                                       :email,
                                                       :phone_number,
                                                       :gender,
                                                       :password,
                                                       :password_confirmation])
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/index.html.erb
<div class="container-fluid">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">
    <div id="map" style="width: 100%; height: 700px;"></div>
  </div>
  <div class="col-md-3">
  </div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%= raw services_json(@services).to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/customers/new.html.erb
<div class="col-md-6">
  <div class="panel panel-primary sign-up-form">
    <div class="panel-heading">
      <h3 class="panel-title">Create a TRIM Account</h3>
    </div>
    <div class="panel-body">
      <%= simple_form_for @customer do |c| %>
        <%= c.simple_fields_for :user do |user| %>
          <%= user.input :first_name %>
          <%= user.input :last_name %>
          <%= user.input :email %>
          <%= user.input :phone_number %>
          <%= user.input :gender %>
          <%= user.input :password %>
          <%= user.input :password_confirmation %>
        <% end %>
       <%= c.button :submit %>
      <% end %>
    </div>
  </div>
</div>

<div class="col-md-6">
  <div class="panel panel-primary sign-up-form">
    <div class="panel-heading">
      <h3 class="panel-title">Or</h3>
    </div>
    <div class="panel-body">
      <%= link_to "Sign Up With Google", sign_in_with_google_path %>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="col-md-12">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">History</h3>
    </div>
    <div class="panel-body">
      <table class="table ">
        <tr>
          <td>
            Service Name
          </td>
          <td>
            Service Rate
          </td>
          <td>
            Appointment Time
          </td>
          <td>
            Booked on
          </td>
          <td>
            reviewed?
          </td>
        </tr>
        <% @bookings.all.order('created_at').each do |booking| %>
        <tr>
          <td><%= link_to "#{booking.service.name}", new_booking_review_path(booking) %></td>
          <td><%= number_to_currency(booking.service.rate) %></td>
          <td><%= booking.time_start.to_formatted_s(:long_ordinal) %> - <%= booking.time_end.to_formatted_s(:long_ordinal) %></td>
          <td><%= booking.created_at.to_formatted_s(:long_ordinal)  %></td>
          <td><%= booking.reviews.present? %> | <%= link_to 'Leave a Review', new_booking_review_path(booking) %></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>