config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :providers, only: [:index, :new, :create]

  resources :services, shallow: true, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:show, :new, :create] do
      resources :payments, only: [:new, :create]
      resources :reviews, only: [:new, :create]
    end
    resources :service_statistics, only: [:show]
  end
  resources :service_statistics, only: [:index]

  resources :bookings, only: [:index]

  resources :customers, only: [:index, :show, :new, :create]

  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback" => "callbacks#google_oauth2_response"
  root "statics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :customer
  has_many :reviews, dependent: :nullify

  validates :time_start, presence: true, uniqueness: true
  validates :time_end, presence: true, uniqueness: true
  validates :service_id, presence: true
  validates :customer_id, presence: true

  def cost
    service.rate
  end

  def provider
    service.provider
  end

  def service_name
    service.name
  end

  def provider_name
    provider.user.full_name
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :user, as: :person, dependent: :destroy
  accepts_nested_attributes_for :user

  has_many :bookings, dependent: :destroy
  has_many :booked_services, through: :bookings, source: :service

  has_many :reviews, dependent: :destroy
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :providers
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :booked_services, through: :bookings, source: :service
  has_many :reviews, dependent: :destroy
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :organizations

  has_one :user, as: :person, dependent: :destroy
  accepts_nested_attributes_for :user

  has_many :services, dependent: :destroy
  has_many :bookings, through: :services
  def sid_list
    services.pluck(:id)
  end

  def previous_year_bookings
    bookings.where(time_end: Time.now.beginning_of_year-1.year..Time.now.end_of_year-1.year)
  end

  def current_year_bookings
    bookings.where(time_end: Time.now.beginning_of_year..Time.now.end_of_year)
  end

  def revenue_data(year)
    revenue_data = []
    months = %w(jan feb mar apr may jun jul aug sep oct nov dec)
    months.each do |month|
      month_revenue = []
      services.each do |service|
        month_revenue << service.monthly_revenue(year, month)
      end
      revenue_data << month_revenue.reduce(:+)
    end
    revenue_data.include?(nil) ? [0] : revenue_data
  end

  def booking_data(year)
    booking_data = []
    months = %w(jan feb mar apr may jun jul aug sep oct nov dec)
    months.each do |month|
      month_booking = []
      services.each do |service|
        month_booking << service.monthly_booking(year, month)
      end
      booking_data << month_booking.reduce(:+)
    end
    booking_data.include?(nil) ? [0] : booking_data
  end

  def annual_revenue
    revenue_data(Time.current.year).reduce(:+)
  end

  def annual_bookings
    booking_data(Time.current.year).reduce(:+)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :customer

  validates :rating, presence: true
  validates :booking_id, presence: true
  validates :customer_id, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :provider
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_many :customers, through: :bookings

  validates :name, presence: true
  validates :rate, presence: true
  validates :location, presence: true
  validates :duration, presence: true
  validates :provider_id, presence: true

  geocoded_by :address
  after_validation :geocode

  def self.provider_services(user)
    Service.where(provider_id: user)
  end

  def monthly_revenue(year, month)
    bookings.where(time_end: Time.mktime(year, month).all_month).count * self.rate
  end

  def monthly_booking(year, month)
    bookings.where(time_end: Time.mktime(year, month).all_month).count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  serialize :google_raw_info
  belongs_to :person, polymorphic: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :person_id, presence: true
  validates :person_type, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.find_from_omniauth(omniauth_data)
    User.where(provider: omniauth_data['provider'],
               uid: omniauth_data['uid']).first
  end

  def self.create_provider_from_omniauth(omniauth_data)
    User.create(uid: omniauth_data['uid'],
                provider: omniauth_data['provider'],
                first_name: omniauth_data['info']['first_name'],
                last_name: omniauth_data['info']['last_name'],
                email: omniauth_data['info']['email'],
                person: Provider.create,
                gender: omniauth_data['extra']['raw_info']['gender'],
                google_raw_info: omniauth_data,
                password: SecureRandom.hex(16))
  end
  def self.create_customer_from_omniauth(omniauth_data)
    User.create(uid: omniauth_data['uid'],
                provider: omniauth_data['provider'],
                first_name: omniauth_data['info']['first_name'],
                last_name: omniauth_data['info']['last_name'],
                email: omniauth_data['info']['email'],
                person: Customer.create,
                gender: omniauth_data['extra']['raw_info']['gender'],
                google_raw_info: omniauth_data,
                password: SecureRandom.hex(16))
  end
end

def self.create_from_omniauth(omniauth_data)
  full_name = omniauth_data["info"]["name"].split
  User.create(uid:                      omniauth_data["uid"],
              provider:                 omniauth_data["provider"],
              first_name:               full_name[0],
              last_name:                full_name[1],
              twitter_consumer_token:   omniauth_data["credentials"]["token"],
              twitter_consumer_secret:  omniauth_data["credentials"]["secret"],
              twitter_raw_data:         omniauth_data,
              password:                 SecureRandom.hex(16)
              )
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  def services_json(services)
    Gmaps4rails.build_markers(services) do |service, marker|
      service_booking = link_to "Book TRIM", new_service_booking_path(service)
      marker.lat        service.latitude
      marker.lng        service.longitude
      marker.infowindow gmaps4rails_service_infowindow(service) + service_booking
    end
  end

  def gmaps4rails_service_infowindow(service)
    "<h4>#{service.name}</h4>" +
    "<h6>#{service.provider.user.first_name}</h6>" +
    "<p>Price: #{cost(service)}</p>"
  end

  def cost(service)
    number_to_currency(service.rate)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TRIM</title>
    <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav id="main-nav" class="nav navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <% if user_signed_in? && user_is_provider? %>
            <%= link_to 'TRIM', providers_path, class:"navbar-brand" %>
          <% elsif user_signed_in? && user_is_customer? %>
            <%= link_to 'TRIM', customers_path, class:"navbar-brand" %>
          <% else %>
            <%= link_to 'TRIM', root_path, class:"navbar-brand" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-left">
          <li><%#= link_to "Add Service", provider_services_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? && user_is_provider? %>
            <li id="loggedin-badge" class="label label-default"><%= "#{current_user.first_name}" %></li>
            <li><%= link_to "Add Service", new_service_path%></li>
            <li><%= link_to "Logout", sessions_path, method: :delete, data: {confirm: "are you sure you want to log out?"} %></li>
          <% elsif user_signed_in? && user_is_customer?%>
            <li id="loggedin-badge" class="label label-default"><%= "#{current_user.first_name}" %></li>
            <li><%= link_to "History", customer_path(current_user) %></li>
            <li><%= link_to "Book a TRIM", bookings_path %></li>
            <li><%= link_to "Logout", sessions_path, method: :delete, data: {confirm: "are you sure you want to log out?"} %></li>
          <% else %>
            <li><%= link_to "Become A TRIMMER", new_provider_path, class:"btn btn-default"%></li>
            <li><%= link_to "Sign Up", new_customer_path, role:"navigation"%></li>
            <li><%= link_to "Login", new_session_path, role:"navigation"%></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>